% Last updated by  Bob Kopp, robert-dot-kopp-at-rutgers-dot-edu, Wed 12 Feb 2014 08:45:53 EST

outputSLRProjections_table_GSLbyyear
outputSLRProjections_table_GSLcomponents
outputSLRProjections_plot_GSL


outputSLRProjections_table_LSLbyyear
outputSLRProjections_table_LSLfactors
outputSLRProjections_table_LSLNorthAmerica

outputSLRProjections_table_sensitivity

outputSLRProjections_plot_components

outputSLRProjections_map_OD
outputSLRProjections_map_LSL
outputSLRProjections_plot_zostoga

outputSLRProjections_plot_meltexcprob
outputSLRProjections_variance_filled

outputSLRProjections_map_fingerprints
outputSLRProjections_table_CMIP5models


COASTLINESFILE=fullfile(PARAMDIR,'coastlines.txt');
outputSLRProjections_map_GIAdomains
outputSLRProjections_table_GIAhyperparameters

